input {
    file {
        path => "/logs/app.log"
        start_position => "end"
        sincedb_path => "/dev/null" # Desativar em produção
    }
}

filter {
    grok {
        match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} - %{LOGLEVEL:level} - \[%{DATA:file}:%{NUMBER:line}\] - %{GREEDYDATA:log_message}" }
    }
    
    date {
        match => [ "timestamp", "yyyy-MM-dd HH:mm:ss" ]
        target => "@timestamp"
    }
}

output {
    elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "pokeapi-logs"
    }

    stdout {
        codec => rubydebug
    }
}

