name: Fastapi - Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fastapi-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Copiar todo Código do Repositório
        uses: actions/checkout@v4

      - name: Instalar poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configurar Python e cache do Poetry
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: poetry

      - name: Baixar Dependências com o Poetry
        run: poetry install --no-interaction --no-root

      - name: Executar teste
        run: poetry run pytest

  docker-build:
    runs-on: ubuntu-latest
    needs: fastapi-tests
      
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
        ports:
          - 9200:9200
        env:
          discovery.type: "single-node"
          bootstrap.memory_lock: "true"
          xpack.security.enabled: "false"
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        options: >-
          --health-cmd "curl -f http://localhost:9200/_cluster/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      kibana:
        image: docker.elastic.co/kibana/kibana:8.11.0
        ports:
          - 5601:5601
        env:
          ELASTICSEARCH_HOST: http://localhost:9200

    steps:
      - name: Copiar o Repositório pro Container
        uses: actions/checkout@v4

      - name: Buildar Container
        run: docker build -t fastapi-app:latest .

      - name: Subir Container
        run: |
          docker rm -f pokeapi-container || true

          docker run -d --network host --name pokeapi-container \
            -e REDIS_HOST="localhost" \
            -e REDIS_PORT="6379" \
            -e ES_HOST="localhost" \
            -e ES_PORT="9200" \
            -e KIBANA_PORT="5601" \
            -e REDIS_URL="redis://localhost:6379/0" \
            fastapi-app:latest

          sleep(5)

          podman logs pokeapi-container

      - name: Verificar se o Container ainda está de Pé
        run: docker ps | grep pokeapi-container | grep Up

      - name: Fazer Requisição na API
        run: curl --fail http://localhost:8000/docs || exit 1

      - name: Listar logs Se FALHAR
        if: failure()
        run: docker logs pokeapi-container
      
      - name: Limpar o Container
        if: always()
        run: docker rm -f pokeapi-container      
